# Generated by Django 5.1.1 on 2024-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_assessmentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswers',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentanswers',
            name='given_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
