# Generated by Django 5.1.1 on 2024-09-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_assessmentanswers_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField()),
                ('json_transcript', models.TextField()),
                ('assessment_transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_transcript', to='assessment.assessmentanswers')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
    ]
